### ISSUE TITLE
多线程导致的局部错点bug

### ISSUE THREAD

**Issue by Diomon** [vincentjzy/OpenCorr#4]
用SIFT+ICGN2 test程序对samples中的oht_cfrp_0.bmp和oht_cfrp_4.bmp进行计算，发现如果开启多线程则计算结果会出现一些局部错点。
单线程计算结果：
![OpenMPNo](https://user-images.githubusercontent.com/33869358/120055224-364b4880-c067-11eb-8698-bf9ef762b487.jpg)
多线程计算结果：
![OpenMPYes](https://user-images.githubusercontent.com/33869358/120055230-39decf80-c067-11eb-83b3-f1fbcb077763.jpg)
经过调试发现feature_affine->compute的结果在多线程计算中会出现这些错点，从而导致后续的ICGN计算失败。

**Comment by cslayers** [comment]
fixed at commit https://github.com/vincentjzy/OpenCorr/commit/cf40dd37f2a994e6ae89beff1d8c05f69f59bf26
