### ISSUE TITLE
why cur_instance->sd_img not be updated in every iterator?

### ISSUE THREAD

**Issue by zhulz** [vincentjzy/OpenCorr#5]
from the deviate , in the formulation g(x2,y2),   x2,y2 are updated when the new  deformation deta is calculated, suppose x2= a0+a1*x+a2*y;   d( g(x2,y2))/da1 = g'(x2,y2)*x,  cur_instance->sd_img ,though x is fixed in every iterator, g'(x2,y2) is changed because x2,y2 is changed ,why sd_img is not changed in every iterator?

**Comment by vincentjzy** [comment]
In the IC-GN algorithm, steepest descent image and the Hessian matrix are calculated in the reference subset. Thus, they don't need to be updated during the iteration. This may be the main reason that the IC-GN algorithm is more computationally efficient than the classic FA-NR algorithm.

**Comment by zhulz** [comment]
thanks，i will learn the icgn algorithm, and study how it works

**Comment by zhulz** [comment]
the icgn algorithm is so clever to omit the calculating costs of  Image gradient interpolation  by the method  x=f(y), d(T(x))/d(x) can use the Image gradient directly instead of  calculating the gradient interpolation .
Thanks Professor Zhang
