### ISSUE TITLE
Library function

### ISSUE THREAD

**Issue by wztneedahelp** [vincentjzy/OpenCorr#6]
Excuse me, does the library function involved in your module have to have an accurate version number? For example, fftw must use version 3.3.9?

**Comment by vincentjzy** [comment]
We didn't test this issue. To my knowledge, the latest releases of some dependent libraries, such as opencv or eigen, experience changes in calling interfaces, which may be quite different from the version we are using. In this case, error may occur during the compiling. Thus, it would be safe and convenient for the users to download the version that we suggest.
