### ISSUE TITLE
关于散斑的问题

### ISSUE THREAD

**Issue by husiluanxiang** [vincentjzy/OpenCorr#7]
你好 请问这个库里面又生成散斑的函数吗，我投影散斑到物体上

**Comment by vincentjzy** [comment]
Unfortunately, OpenCorr has not included speckle pattern generation yet. There is a good software (Glare) that can do this work. You may find the information here (https://doi.org/10.1016/j.optlaseng.2021.106766)

**Comment by husiluanxiang** [comment]
ok  thanks
